apiVersion: apps/v1
kind: Deployment
metadata:
  name: caas
  labels:
    app: caas
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: caas
  template:
    metadata:
      labels:
        app: caas
    spec:
      containers:
      - name: caas
        image: redbridge/caas:2
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 8080
